"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-06 04:14:20.445350

"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('CHANGE_ORDER', 'PURCHASE_ORDER', name='approvalentitytype', native_enum=False, length=32), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PROJECT_MANAGER', 'EXECUTIVE', 'FINANCE', 'VIEWER', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('threshold_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('original_contract_value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('budget_control', sa.Enum('STOP', 'WARN', 'IGNORE', name='budgetcontrolaction', native_enum=False, length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PROJECT_MANAGER', 'EXECUTIVE', 'FINANCE', 'VIEWER', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vendor_type', sa.Enum('SUBCONTRACTOR', 'SUPPLIER', name='vendortype', native_enum=False, length=32), nullable=False),
    sa.Column('trade', sa.String(length=120), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('CHANGE_ORDER', 'PURCHASE_ORDER', name='approvalentitytype', native_enum=False, length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('required_role', sa.Enum('ADMIN', 'PROJECT_MANAGER', 'EXECUTIVE', 'FINANCE', 'VIEWER', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus', native_enum=False, length=32), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_entity_id'), 'approval_requests', ['entity_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_entity_type'), 'approval_requests', ['entity_type'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_hash'), 'audit_events', ['hash'], unique=False)
    op.create_table('budget_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('cost_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('LABOR', 'MATERIAL', 'EQUIPMENT', 'SUBCONTRACT', 'GENERAL_CONDITIONS', name='costcategory', native_enum=False, length=32), nullable=False),
    sa.Column('original_budget', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'cost_code', name='uq_budget_project_costcode')
    )
    op.create_index(op.f('ix_budget_lines_project_id'), 'budget_lines', ['project_id'], unique=False)
    op.create_table('change_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('co_type', sa.Enum('PCO', 'OCO', 'SCO', name='changeordertype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PRICING', 'SUBMITTED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'CONVERTED', 'VOID', name='changeorderstatus', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('origin_pco_id', sa.Integer(), nullable=True),
    sa.Column('schedule_impact_days', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['origin_pco_id'], ['change_orders.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'number', name='uq_co_project_number')
    )
    op.create_index(op.f('ix_change_orders_project_id'), 'change_orders', ['project_id'], unique=False)
    op.create_index(op.f('ix_change_orders_status'), 'change_orders', ['status'], unique=False)
    op.create_table('forecast_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('method', sa.Enum('REMAINING_BUDGET', 'CPI', name='forecastmethod', native_enum=False, length=32), nullable=False),
    sa.Column('total_current_budget', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_committed', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_actual', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_etc', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_eac', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_vac', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_snapshots_project_id'), 'forecast_snapshots', ['project_id'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'endpoint', 'user_id', name='uq_idem_key_endpoint_user')
    )
    op.create_index(op.f('ix_idempotency_records_key'), 'idempotency_records', ['key'], unique=False)
    op.create_table('change_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_order_id', sa.Integer(), nullable=False),
    sa.Column('budget_line_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['budget_line_id'], ['budget_lines.id'], ),
    sa.ForeignKeyConstraint(['change_order_id'], ['change_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_order_lines_change_order_id'), 'change_order_lines', ['change_order_id'], unique=False)
    op.create_table('cost_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_line_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['budget_line_id'], ['budget_lines.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_entries_budget_line_id'), 'cost_entries', ['budget_line_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'CLOSED', 'CANCELLED', name='purchaseorderstatus', native_enum=False, length=32), nullable=False),
    sa.Column('source_change_order_id', sa.Integer(), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_change_order_id'], ['change_orders.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'number', name='uq_po_project_number')
    )
    op.create_index(op.f('ix_purchase_orders_project_id'), 'purchase_orders', ['project_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('budget_line_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['budget_line_id'], ['budget_lines.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_lines_purchase_order_id'), 'purchase_order_lines', ['purchase_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_order_lines_purchase_order_id'), table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_project_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_cost_entries_budget_line_id'), table_name='cost_entries')
    op.drop_table('cost_entries')
    op.drop_index(op.f('ix_change_order_lines_change_order_id'), table_name='change_order_lines')
    op.drop_table('change_order_lines')
    op.drop_index(op.f('ix_idempotency_records_key'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_forecast_snapshots_project_id'), table_name='forecast_snapshots')
    op.drop_table('forecast_snapshots')
    op.drop_index(op.f('ix_change_orders_status'), table_name='change_orders')
    op.drop_index(op.f('ix_change_orders_project_id'), table_name='change_orders')
    op.drop_table('change_orders')
    op.drop_index(op.f('ix_budget_lines_project_id'), table_name='budget_lines')
    op.drop_table('budget_lines')
    op.drop_index(op.f('ix_audit_events_hash'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_entity_type'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_entity_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('approval_rules')
    # ### end Alembic commands ###
